branches:
  only:
    - master
    - /^release-.*$/

language: swift
xcode_scheme: Development
xcode_project: ContinuousCI_CD.xcworkspace
osx_image: xcode11
sudo: false

cache:
  - bundler
  - cocoapods

env: 
  global:
    - WORKSPACE="ContinuousCI_CD.xcworkspace"
    - SCHEME="Development"
    - IOS_SDK="iphonesimulator13.1"
  matrix:
    - DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=13.1"
    - DESTINATION="platform=iOS Simulator,name=iPad Pro (11-inch),OS=13.1"

jobs:
  include:
    - &iOS
      stage: iOS Build
      env: SWIFT=5.0
      name: iOS Xcode11 Swift5
      xcode_project: "$WORKSPACE"
      xcode_scheme: "$SCHEME"
      xcode_sdk: "$IOS_SDK"
      xcode_destination: "$DESTINATION"
    - <<: *iOS
      script: xcodebuild clean build -configuration Debug
      
install:
  - bundle install --deployment
  - bundle exec pod --version
  - bundle exec pod repo update --verbose
  - bundle exec pod install

before_script:
  - set -o pipefail