language: swift
xcode_scheme: Production
xcode_project: ContinuousCI_CD.xcworkspace
sudo: false

cache:
  - bundler
  - cocoapods

jobs:
  include:
    - &iOS
      stage: iOS
      osx_image: xcode11
      name: iPhone SE
      xcode_destination: 'OS=13,name=iPhone SE'
    - <<: *iOS
      osx_image: xcode11
      name: iPad
      xcode_destination: 'OS=13,name=iPad Pro (11-inch)'

install:
  - bundle install --deployment
  - bundle exec pod --version
  - bundle exec pod repo update --verbose
  - bundle exec pod install

script:
  - echo Test