branches:
  only:
    - master
    - /^release-.*$/

language: swift
osx_image: xcode11
sudo: false

cache:
  - bundler
  - cocoapods

env: 
  global:
    - WORKSPACE="ContinuousCI_CD.xcworkspace"
    - SCHEME="Development"
    - IOS_SDK="iphonesimulator13.0"
  matrix:
    - SDK="$IOS_SDK" DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=13.0"
    - SDK="$IOS_SDK" DESTINATION="platform=iOS Simulator,name=iPad Pro (11-inch),OS=13.0"

before_script:
  - set -o pipefail
      
install:
  - bundle install --deployment
  - bundle exec pod --version
  - bundle exec pod repo update --verbose
  - bundle exec pod install

script:
  - xcodebuild clean build test
    -workspace "$WORKSPACE"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug

after_success:
  - bash <(curl -s https://codecov.io/bash) -t "$CODE_COV_TOKEN"

notifications:
  slack:
    rooms:
    - assincontinuousci:HLkeWcwYvimTS35OqW7De3aF#general
