branches:
  only:
    - master
    - /^release-.*$/

language: swift
xcode_scheme: Development
osx_image: xcode11
sudo: false

cache:
  - bundler
  - cocoapods

env: 
  global:
    - WORKSPACE="ContinuousCI_CD.xcworkspace"
    - SCHEME="Development"
  matrix:
    - SDK="iphonesimulator13.0" DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=13.0"
    # - SDK="$IOS_SDK_13_1" DESTINATION="platform=iOS Simulator,name=iPad Pro (11-inch),OS=13.1"

jobs:
  include:
    - &iOS      
      name: iOS Xcode11 Swift5
    - <<: *iOS
      name: testss
      script: xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug
      
install:
  - bundle install --deployment
  - bundle exec pod --version
  - bundle exec pod repo update --verbose
  - bundle exec pod install

before_script:
  - set -o pipefail