# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

import './VersionFastFile'
import './AppleAccounts'

default_platform(:ios)

PRODUCTION_CONFIG_PATH = 'fastlane/BuildConfiguration/Production.xcconfig'
VERSION_CONFIG_PATH = 'fastlane/BuildConfiguration/Common/Versions.xcconfig'
RELEASE_NOTE_PATH = 'fastlane/build/build_notes.md'

lane_context[SharedValues::BUILD_NUMBER] = get_xcconfig_value(
  path: VERSION_CONFIG_PATH,
  name: 'LONG_BUNDLE_VERSION'
)

lane_context[SharedValues::VERSION_NUMBER] = get_xcconfig_value(
  path: VERSION_CONFIG_PATH,
  name: 'BUNDLE_VERSION'
) 

lane_context['app_name'] = get_xcconfig_value(
  path: PRODUCTION_CONFIG_PATH,
  name: 'PRODUCT_NAME'
) 



platform :ios do  
  desc "Push a new release build to the App Store"
  lane :beta do | options |
    build
    crashlytics(
      crashlytics_path: './Pods/Crashlytics/Crashlytics.framework',
      api_token: '01a8a326ef40f1e4010685ff3fe389ad91c04149',
      build_secret: '4f7b6feb7d1e7498160d8920b040828ccb45071a71a170c4006a4075e69fd0c8',
      ipa_path: "#{lane_context[SharedValues::IPA_OUTPUT_PATH]}",
      groups: options[:groups],
      notifications: options[:notifications],
      notes_path: RELEASE_NOTE_PATH,
      emails: 'kimtaesoo188@gmail.com' # testers
    )
  end 

  desc "Push a new release build to the App Store"
  private_lane :build do | options |
    ensure_git_status_clean

    match(type: 'appstore', readonly: true)
    build_ios_app(
      scheme: "Production",
      clean: true,
      output_directory: "fastlane/build", 
      output_name: "#{lane_context['app_name']}.ipa"
    )
    puts "generate ipa: #{lane_context[SharedValues::IPA_OUTPUT_PATH]}"
  end 

  desc "Push a new release build to the App Store"
  lane :appstore do | options |
    # puts "determine version_number: [#{lane_context[SharedValues::VERSION_NUMBER]}] build_number: [#{lane_context[SharedValues::BUILD_NUMBER]}]"

    # produce(
    #   app_name:lane_context['app_name'],
    #   enable_services: {
    #     push_notification: "on"
    #   }
    # )
  
    # precheck
    # snapshot
    build
    deliver(
      force:true,
      username:"kimtaesoo1888@gmail.com",
      ipa:lane_context[SharedValues::IPA_OUTPUT_PATH] ,
      app_version:lane_context[SharedValues::VERSION_NUMBER]
    )
  end
end

